### ISSUE TITLE
PPOCRLabel保存识别结果时可否将合并保存改为单独保存？

### ISSUE THREAD

**Issue by sls463** [Evezerest/AutoLabel#36]
当前PPOCRLabel 点“保存识别结果” 后会将所有图片识别出来的文本保存到一个 rec_gt.txt 文件中，请问能不能设置为各个图片识别出来的文本进行单独保存呢？谢谢
例如：001.jpg、002.jpg、003.jpg、004.jpg、005.jpg
识别结果保存为：001.txt、002.txt、003.txt、004.txt、005.txt

**Comment by Evezerest** [comment]
目前不可以，因为现有的输出格式是直接用于PaddleOCR训练的。当然也可以自己再写个脚本处理一下。
