### ISSUE TITLE
Annotate with another language

### ISSUE THREAD

**Issue by congphu2511995** [Evezerest/AutoLabel#41]
Can i use another language for text annotation (for example vietnamese)?
Thank you for this useful tool.

**Comment by Evezerest** [comment]
Yes, PPOCRLabel have a build-in OCR engine `paddleocr`, which has already supported the Vietnamese recognition, you can specify the `lang` parameter to `vi` [here](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.4/PPOCRLabel/PPOCRLabel.py#L117), more languages and abbreviations supported by `paddleocr` can be found [here](https://github.com/PaddlePaddle/PaddleOCR/blob/44ea70d5fcf0fc76d7ef3a2579f751e64acc5070/doc/doc_en/multi_languages_en.md#5-support-languages-and-abbreviations)

However, we didn't use much data when training multi-language models. If you are interested in improving the multi-language model, pls let me know, we are happy to give you some advice.
